'use client';
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from '../components/sidebar';
import { Toaster } from "react-hot-toast";
import { store } from "@/store";
import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <Provider store={store}>
        <body className={inter.className}>
          <Toaster />
          {/* <CheckUserInfo /> */}
          <div style={{ paddingLeft: '60px', backgroundColor: '' }}>
            {children}
          </div>
          <Sidebar />
        </body>
      </Provider>

    </html>
  );
}
